//
// Created by mozzicator on 16/01/20.
//

#ifndef INC_02_APPROVVIGIONAMENTO_COMPONENT_H
#define INC_02_APPROVVIGIONAMENTO_COMPONENT_H


class Component {

};


#endif //INC_02_APPROVVIGIONAMENTO_COMPONENT_H
